version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout

      - run:
          command: sudo apt-get update
      - run:
          command: sudo apt-get install -y bc bison build-essential curl flex g++-multilib gcc-multilib gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zlib1g-dev libisl-dev
      - run:
          command: sudo bash ./build_Z010D.sh
